name: nuenenen
description: X-Platform App für die Pfadiabteilung Nünenen

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.1.3+14

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  fluro: ^1.6.4
  http: ^0.13.4
  firebase_messaging: ^7.0.3
  permission_handler: ^5.1.0+2
  flutter_html: ^1.3.0
  url_launcher: ^6.0.5
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
