name: nuenenen
description: X-Platform App für die Pfadiabteilung Nünenen

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.2.0+14

environment:
  sdk: '<4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  fluro: ^2.0.5
  http: ^0.13.5
  fluttertoast: ^8.2.1
  shared_preferences: ^2.1.0
  permission_handler: ^10.2.0
  flutter_html: ^2.2.1
  url_launcher: ^6.1.10
  firebase_messaging: ^14.4.1
  firebase_core: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

