name: nuenenen
description: X-Platform App für die Pfadiabteilung Nünenen

version: 3.1.2+13

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluro: ^2.0.3
  http: ^0.13.0
  firebase_messaging: ^7.0.3
  permission_handler: ^5.1.0+2
  flutter_html: ^1.3.0
  url_launcher: ^6.0.2
  shared_preferences: ^2.0.3
  fluttertoast: ^7.1.8
  qr_code_scanner: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  ios: true
  android: true
  image_path: "assets/launcher/icon.png"
