name: nuenenen
description: X-Platform App für die Pfadiabteilung Nünenen

version: 3.1.3+14

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  fluro: ^2.0.3
  http: ^0.13.3
  firebase_messaging: ^10.0.0
  permission_handler: ^5.1.0+2
  flutter_html: ^1.3.0
  url_launcher: ^6.0.5
  shared_preferences: ^2.0.6
  fluttertoast: ^8.0.7
  qr_code_scanner: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  ios: true
  android: true
  image_path: "assets/launcher/icon.png"
